export const allows = [
  "bluetooth",
  "camera",
  "clipboard-write",
  "clipboard-read",
  "geolocation",
  "hid",
  "micropohone",
  "midi",
  "fullscreen",
  "payment",
  "picture-in-picture",
  "usb",
  "web-share",
];
